### ISSUE TITLE
Create a dib-training gcalendar

### ISSUE THREAD

**Issue by ctb** [ged-lab/dib-training#10]
Michael says:

```
I'd create a new calendar and then share it with whoever. You can also
share it with a Google Group which will share it with each account
individually.

https://support.google.com/calendar/answer/37095?hl=en  
https://support.google.com/calendar/answer/37082?hl=en
```

**Comment by jessicalumian** [comment]
Edit: this calendar was only for the iPlant + others week, my comment below is the calendar we should use.

Here's a first shot. 
https://www.google.com/calendar/embed?src=0an478kmsc0ue87rl89b07d2ns%40group.calendar.google.com&ctz=America/New_York

I set the timezone to Pacific and put the workshop start times at 8a or 9a (whatever was on the eventbrite), but the times show up a few hours off for me. Not sure if that is because I'm still in an Eastern time zone location.

**Comment by jessicalumian** [comment]
This will be where I add all training events:

https://calendar.google.com/calendar/embed?src=mqcgc13fqifh9ocb7l8novguik%40group.calendar.google.com&ctz=America/Los_Angeles

I don't see an easy way to share the calendar with people, other than manually inserting each email address.  If we can get a list of people interested (perhaps via email) I can add them to the calendar.  We can also embed the calendar in our website.

**Comment by ctb** [comment]
can we just make it public?

**Comment by jessicalumian** [comment]
It is public now, but I don't think people can add it to their own google calendars without it being "shared" (email address entered on page).
